### ISSUE TITLE
Line wrapping toggle not working

### ISSUE THREAD

**Issue by aniravi24** [Effect-TS/website#57]
![image](https://user-images.githubusercontent.com/5902976/234659306-1b77a04b-bdc1-4ffd-a790-f4db1c14121f.png)

The toggle on the top right of the code block to line wrap doesn't do anything. Potentially due to the custom TS snippets we use with twoslash.

**Comment by IMax153** [comment]
Yea this is an issue with the custom TS snippets (i.e. problem with `shiki-twoslash`). Will need to investigate further how to fix it.

**Comment by IMax153** [comment]
The issue seems to be that when the button is clicked, the [click handler is indeed applying the proper dataset attribute](https://github.com/shuding/nextra/blob/272c472d838da5d935b01807f2fe03dc757a14d5/packages/nextra/src/components/pre.tsx#L19) to the DOM, but the [styles that are supposed to be applied when the button is clicked](https://github.com/shuding/nextra/blob/272c472d838da5d935b01807f2fe03dc757a14d5/packages/nextra/styles/code-block.css#L40) are not having the intended effect.

So more likely than not some shiki CSS is probably overriding the word wrap behavior that is supposed to be applied when the button is clicked.

**Comment by aniravi24** [comment]
I wonder if `twoslash.css` could have something added in it that would allow this to apply correctly.
