### ISSUE TITLE
Effect Website Playground fails to load n Firefox

### ISSUE THREAD

**Issue by ryansobol** [Effect-TS/website#793]
### What version of Effect is running?

N/A

### What steps can reproduce the bug?

Visited the [Effect Playground](https://effect.website/play) in Firefox v129.

### What is the expected behavior?

For the Effect Playground to finish loading its editor.

### What do you see instead?

The Effect Playground's "Loading editor..." spinner spins forever.

<img width="1392" alt="Screenshot 2024-08-01 at 09 13 44" src="https://github.com/user-attachments/assets/eb331d12-1735-4cad-b759-c5ee111790ae">

There is one `Uncaught DOMException: The operation is insecure.` error in Firefox's console.

<img width="1429" alt="Screenshot 2024-08-01 at 09 15 19" src="https://github.com/user-attachments/assets/ff3b9a1a-3d0c-4dc9-a66f-1f9d3f9c3378">

**Comment by IMax153** [comment]
Unfortunately, [Webcontainers](https://webcontainers.io) (which is the technology we use to power the NodeJS runtime for the playground) seems to only have [alpha support for Firefox](https://webcontainers.io/guides/browser-support#firefox) at this time, which is due to Firefox only providing limited support for cross-origin isolation (required for Webcontainers to run).
